# Generated by Django 4.2.1 on 2023-06-08 15:15

from django.db import migrations, models
import django.db.models.deletion
import negocioCompra.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompraNegocio',
            fields=[
                ('id_Compra', models.AutoField(primary_key=True, serialize=False)),
                ('F_compra', models.DateTimeField(auto_now_add=True)),
                ('hora', models.TimeField(default=negocioCompra.models.hrsDetail)),
                ('cantidad_total', models.PositiveIntegerField()),
                ('Total_a_pagar', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('ID_PRODUCTO', models.AutoField(primary_key=True, serialize=False)),
                ('nombreProducto', models.CharField(max_length=100)),
                ('precio', models.IntegerField(default=100)),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('RUT_PROVEEDOR', models.AutoField(primary_key=True, serialize=False)),
                ('NOMBRE_PROVEEDOR', models.CharField(max_length=200)),
                ('TELEFONO_PROVEEDOR', models.CharField(max_length=200)),
                ('DIRECCION', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Detalle_compra',
            fields=[
                ('id_detalle', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('compra_Negocio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='negocioCompra.compranegocio')),
            ],
        ),
        migrations.AddField(
            model_name='compranegocio',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='negocioCompra.producto'),
        ),
        migrations.AddField(
            model_name='compranegocio',
            name='proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='negocioCompra.proveedor'),
        ),
    ]
